version: '3.9'

services:
  react:
    build:
      context: .
      dockerfile: ./Dockerfiles/development/Dockerfile
    container_name: my-react-app-dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "${PWD}/my-react-app/:/app"
      - "${PWD}/my-react-app/node_modules"
    networks:
      - dwr-network

networks:
  dwr-network:
    driver: bridge
