version: "3.9"

services:
  mysql:
    image: mysql:8.0.28
    container_name: dwr-mysql-dev
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_USER=${MYSQL_USER:-wordpress}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
    volumes:
      - "${PWD}/dbdata:/var/lib/mysql"
    command: "--default-authentication-plugin=mysql_native_password"
    networks:
      - dwr-network-dev

  wordpress:
    image: wordpress:5.9.3-fpm-alpine
    container_name: dwr-wordpress-dev
    restart: always
    ports:
      - "9000:9000"
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=${MYSQL_USER:-wordpress}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD:-password}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
    volumes:
      - "${PWD}/wordpress:/var/www/html"
    depends_on:
      - mysql
    networks:
      - dwr-network-dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: dwr-phpmyadmin-dev
    restart: always
    ports:
      - "9090:80"
    environment:
      - PMA_HOST=${PMA_HOST:-mysql}
      - PMA_PORT=${PMA_PORT:-3306}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    networks:
      - dwr-network-dev
  react:
    build:
      context: .
      dockerfile: ./Dockerfiles/development/Dockerfile
    container_name: my-react-app-dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "${PWD}/my-react-app/:/app"
      - "${PWD}/my-react-app/node_modules"
    networks:
      - dwr-network-dev

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: dwr-nginx-dev
    restart: always
    ports:
      - "80:80"
    volumes:
      - "${PWD}/wordpress:/var/www/html"
      - "${PWD}/nginx:/etc/nginx/conf.d"
    depends_on:
      - wordpress
    networks:
      - dwr-network-dev

volumes:
  wordpress:
  dbdata: 

networks:
  dwr-network-dev:
    driver: bridge
